### PR TITLE
error message added for empty task

### PR DESCRIPTION
**Pull request by abee62**
When you try adding empty task, now the error message will pop up. This will be only start after adding at least one task or typing something in the text box as the add task button is disabled initially.

### CODE REVIEW

**Comment by varunherlekar** [comment]
Amazing Work @abee62

**Comment by abee62** [comment]
Thank you @varunherlekar !!!

**Comment by varunherlekar** [comment]
@all-contributors please add @abee62 for code

**Comment by varunherlekar** [comment]
@all-contributors please add @abee62 for code

**Pull request merged**
