### PR TITLE
Added "mark as important" functionality

### PR DESCRIPTION
**Pull request by jackwebdev**
- Adds todo to the top when marked as important.
- Style changes to todo when marked as important.
- Renamed the removeItem event function to handleToDoButtonClick

### CODE REVIEW

**Comment by jackwebdev** [comment]
This is my first time making a pull request. I hope I done it right! 🤞

**Comment by varunherlekar** [comment]
Hey, @jackwebdev there are few conflicts in app.js file. Can you please fetch the upstream and add a PR again.

**Comment by jackwebdev** [comment]
I fixed the issues within the conflict? I hope that is the right way of doing it?

**Comment by varunherlekar** [comment]
Yes.

**Comment by varunherlekar** [comment]
Great Job @jackwebdev . It is working perfectly. :)

**Pull request merged**
