### PR TITLE
Fix: UI Issue #2 & some more fixes for better UI/UX

### PR DESCRIPTION
**Pull request by icoderharshit**
Updated the required styles in the stylesheet (style.css) and a few bootstrap breakpoints classes in html file (index.html) . Please, check @varunherlekar , This must resolve issue #2  and also a bit of some more quick UI/UX fixes to make the website more intuitive. Also, I have added the required comments in the stylesheet wherever needed.
Hope you'll appreciate the changes and help me get my first PR for Hacktoberfest '21 merged. Thankyou :) Looking to contribute more in this amazing project @varunherlekar

### CODE REVIEW

**Comment by varunherlekar** [comment]
Hey @icoderharshit, Thanks for contributing. Please create more issues if you want to contribute more, I will assign them to you.

**Comment by icoderharshit** [comment]
Sure thing @varunherlekar Thank you, man :)

**Comment by varunherlekar** [comment]
@all-contributors please add @icoderharshit  for design

**Comment by varunherlekar** [comment]
@all-contributors please add @icoderharshit for design

**Pull request merged**
